export const pagesRoutes = [
  ["v-8daa1a0e","/",{"t":"电子数据取证Wiki | Forensics-Wiki","i":"home"},["/index.html","/README.md"]],
  ["v-2e3eac9e","/slides.html",{"t":"Slide page","i":"slides"},["/slides","/slides.md"]],
  ["v-e28010b2","/demo/bitlocker.html",{"t":"Bitlocker加密与解密"},["/demo/bitlocker","/demo/bitlocker.md"]],
  ["v-2e04c70c","/demo/efs.html",{"t":"EFS加密与解密"},["/demo/efs","/demo/efs.md"]],
  ["v-c151bf32","/demo/encrypt.html",{"t":"Encryption Article"},["/demo/encrypt","/demo/encrypt.md"]],
  ["v-1473bf53","/demo/",{"t":"Windows取证","i":"windows"},["/demo/index.html","/demo/README.md"]],
  ["v-36a02201","/forensics-apk/",{"t":"apk分析","i":"apk"},["/forensics-apk/index.html","/forensics-apk/README.md"]],
  ["v-53f3090e","/forensics-android/",{"t":"安卓取证","i":"android"},["/forensics-android/index.html","/forensics-android/README.md"]],
  ["v-0f22dd03","/forensics-apple/",{"t":"苹果取证","i":"apple"},["/forensics-apple/index.html","/forensics-apple/README.md"]],
  ["v-798cba0d","/forensics-base/file.html",{"t":"证据文件格式"},["/forensics-base/file","/forensics-base/file.md"]],
  ["v-6279fd58","/forensics-base/ftkfz.html",{"t":"镜像仿真-FTK Imager"},["/forensics-base/ftkfz","/forensics-base/ftkfz.md"]],
  ["v-ae467874","/forensics-base/img.html",{"t":"镜像制作"},["/forensics-base/img","/forensics-base/img.md"]],
  ["v-c528ee60","/forensics-base/",{"t":"基础工具使用","i":"tool"},["/forensics-base/index.html","/forensics-base/README.md"]],
  ["v-b6276f06","/forensics-base/sha.html",{"t":"哈希值"},["/forensics-base/sha","/forensics-base/sha.md"]],
  ["v-6c477499","/forensics-base/veracrypt.html",{"t":"VeraCrypt使用方法"},["/forensics-base/veracrypt","/forensics-base/veracrypt.md"]],
  ["v-c4e948f8","/forensics-disk/",{"t":"磁盘分析","i":"harddisk"},["/forensics-disk/index.html","/forensics-disk/README.md"]],
  ["v-36a210cb","/forensics-exe/",{"t":"恶意程序分析","i":"exe"},["/forensics-exe/index.html","/forensics-exe/README.md"]],
  ["v-7351af11","/forensics-linux/111.html",{"t":"Markdown Enhance"},["/forensics-linux/111","/forensics-linux/111.md"]],
  ["v-2184c2a9","/forensics-linux/",{"t":"Linux取证"},["/forensics-linux/index.html","/forensics-linux/README.md"]],
  ["v-0aa45508","/forensics-liuliang/",{"t":"流量分析","i":"liuliang"},["/forensics-liuliang/index.html","/forensics-liuliang/README.md"]],
  ["v-37b3b71c","/forensics-yinru/",{"t":"电子数据取证引入","i":"yinru"},["/forensics-yinru/index.html","/forensics-yinru/README.md"]],
  ["v-fffb8e28","/guide/",{"t":"Guide","i":"creative"},["/guide/index.html","/guide/README.md"]],
  ["v-e5acbc46","/forensics-ram/install.html",{"t":"安装"},["/forensics-ram/install","/forensics-ram/install.md"]],
  ["v-12ab5d19","/forensics-ram/introduce.html",{"t":"介绍"},["/forensics-ram/introduce","/forensics-ram/introduce.md"]],
  ["v-36a7a43f","/forensics-ram/",{"t":"内存取证","i":"ram"},["/forensics-ram/index.html","/forensics-ram/README.md"]],
  ["v-3ff8661e","/forensics-ram/use.html",{"t":"基本用法"},["/forensics-ram/use","/forensics-ram/use.md"]],
  ["v-06d9f5f5","/forensics-ram/windows.html",{"t":"Windows命令参考"},["/forensics-ram/windows","/forensics-ram/windows.md"]],
  ["v-2d0ad528","/zh/",{"t":"Forensics Wiki","i":"home"},["/zh/index.html","/zh/README.md"]],
  ["v-269ae70f","/zh/slides.html",{"t":"幻灯片页","i":"slides"},["/zh/slides","/zh/slides.md"]],
  ["v-177e1f06","/guide/bar/baz.html",{"t":"Baz","i":"info"},["/guide/bar/baz","/guide/bar/baz.md"]],
  ["v-5d5c2d30","/guide/bar/",{"t":"Bar feature","i":"creative"},["/guide/bar/index.html","/guide/bar/README.md"]],
  ["v-0b6fc5f8","/guide/foo/ray.html",{"t":"Ray","i":"config"},["/guide/foo/ray","/guide/foo/ray.md"]],
  ["v-5d5821d6","/guide/foo/",{"t":"Foo feature","i":"config"},["/guide/foo/index.html","/guide/foo/README.md"]],
  ["v-c1942916","/zh/demo/disable.html",{"t":"布局与功能禁用","i":"config"},["/zh/demo/disable","/zh/demo/disable.md"]],
  ["v-65c00218","/zh/demo/encrypt.html",{"t":"密码加密的文章","i":"lock"},["/zh/demo/encrypt","/zh/demo/encrypt.md"]],
  ["v-36295574","/zh/demo/markdown.html",{"t":"Markdown 展示","i":"markdown"},["/zh/demo/markdown","/zh/demo/markdown.md"]],
  ["v-62ced1a6","/zh/demo/page.html",{"t":"页面配置","i":"page"},["/zh/demo/page","/zh/demo/page.md"]],
  ["v-2b64e284","/zh/demo/",{"t":"主要功能与配置演示","i":"discover"},["/zh/demo/index.html","/zh/demo/README.md"]],
  ["v-47357bdb","/zh/guide/",{"t":"指南","i":"creative"},["/zh/guide/index.html","/zh/guide/README.md"]],
  ["v-1e317375","/zh/guide/bar/baz.html",{"t":"Baz","i":"info"},["/zh/guide/bar/baz","/zh/guide/bar/baz.md"]],
  ["v-763c1cd7","/zh/guide/bar/",{"t":"Bar 功能","i":"creative"},["/zh/guide/bar/index.html","/zh/guide/bar/README.md"]],
  ["v-00fb7173","/zh/guide/foo/ray.html",{"t":"Ray","i":"config"},["/zh/guide/foo/ray","/zh/guide/foo/ray.md"]],
  ["v-763e2284","/zh/guide/foo/",{"t":"Foo 功能","i":"config"},["/zh/guide/foo/index.html","/zh/guide/foo/README.md"]],
  ["v-3706649a","/404.html",{"t":""},["/404"]],
]
