export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"电子数据取证Wiki","i":"home"},["/README.md"]],
  ["v-68fb20c0","/android/cc.html",{"y":"a","t":"Android数据存储技术","i":"database","O":2},[":md"]],
  ["v-7c91bde8","/android/dx.html",{"y":"a","t":"彩信/短信取证","i":"message","O":1},[":md"]],
  ["v-c1f0fcce","/android/",{"y":"a","t":"安卓取证","i":"fab fa-android"},["/android/README.md"]],
  ["v-6f4cca1f","/demo/cj.html",{"y":"a","t":"Forensics-Wiki常见问题","i":"circle-question","O":2},[":md"]],
  ["v-1473bf53","/demo/",{"y":"a","t":"引入","i":"network-wired"},["/demo/README.md"]],
  ["v-6cbb2af0","/demo/sq.html",{"y":"a","t":"商业取证软件授权问题","i":"file","O":3},[":md"]],
  ["v-08bca6ad","/demo/yr.html",{"y":"a","t":"电子数据取证引入","i":"heading","O":1},[":md"]],
  ["v-260c2c94","/base/dd.html",{"y":"a","t":"镜像仿真-DD、E01","i":"info","O":5},[":md"]],
  ["v-4350e0b0","/base/gs.html",{"y":"a","t":"证据文件格式","i":"file","O":3},[":md"]],
  ["v-2b52fe06","/base/hash.html",{"y":"a","t":"哈希值","i":"hashtag","O":1},[":md"]],
  ["v-1455d425","/base/",{"y":"a","t":"取证基础","i":"laptop-code"},["/base/README.md"]],
  ["v-1b0daba7","/base/time.html",{"y":"a","t":"常见的时间戳转换","i":"clock","O":7},[":md"]],
  ["v-46f102f2","/base/vc.html",{"y":"a","t":"VeraCrypt使用方法","i":"lock","O":2},[":md"]],
  ["v-78a344bc","/base/win.html",{"y":"a","t":"镜像仿真-Windows Server","i":"info","O":6},[":md"]],
  ["v-51403c58","/base/zz.html",{"y":"a","t":"镜像制作","i":"wand-magic","O":4},[":md"]],
  ["v-56dc102a","/ios/dx.html",{"y":"a","t":"彩信/短信取证","i":"message","I":0},[":md"]],
  ["v-7448383b","/ios/",{"y":"a","t":"IOS取证","i":"fab fa-apple"},["/ios/README.md"]],
  ["v-0fcdf09a","/linux/basecommand.html",{"y":"a","t":"基础命令","i":"terminal","O":2},[":md"]],
  ["v-001e82c0","/linux/cdn.html",{"y":"a","t":"CDN基础","i":"shield","O":3},[":md"]],
  ["v-3a5070e2","/linux/intr.html",{"y":"a","t":"介绍","i":"play","O":1},[":md"]],
  ["v-f0383c18","/linux/",{"y":"a","t":"Linux&服务器取证","i":"fab fa-linux"},["/linux/README.md"]],
  ["v-3de34fb7","/volatility/base.html",{"y":"a","t":"基本用法","i":"star","O":3},[":md"]],
  ["v-3d6a4aa2","/volatility/install.html",{"y":"a","t":"安装","i":"hand","O":2},[":md"]],
  ["v-6b9c0bff","/volatility/js.html",{"y":"a","t":"介绍","i":"play","O":1},[":md"]],
  ["v-5aca0811","/volatility/",{"y":"a","t":"内存取证","i":"memory"},["/volatility/README.md"]],
  ["v-c533b1de","/volatility/winvol.html",{"y":"a","t":"Windows命令参考","i":"fab fa-windows","O":4},[":md"]],
  ["v-32efb0d9","/windows/bitlocker.html",{"y":"a","t":"Bitlocker加密与解密","i":"unlock","O":1},[":md"]],
  ["v-74f4a32c","/windows/efs.html",{"y":"a","t":"EFS加密与解密","i":"unlock","O":2},[":md"]],
  ["v-d7a4cff6","/windows/",{"y":"a","t":"Windows取证","i":"fab fa-windows"},["/windows/README.md"]],
  ["v-ac6d791e","/writeup/2022changancup.html",{"y":"a","t":"第四届长安杯电子数据取证大赛Writeup","i":"award","O":1},[":md"]],
  ["v-befc5eac","/writeup/2023pgs.html",{"y":"a","t":"2023首届盘古石杯电子数据取证大赛","i":"award","O":2},[":md"]],
  ["v-689a56ae","/writeup/",{"y":"a","t":"赛题Writeup","i":"trophy"},["/writeup/README.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
]
